/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  typescript: {
    ignoreBuildErrors: false,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'placehold.co',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'picsum.photos',
        port: '',
        pathname: '/**',
      },
    ],
  },
  experimental: {
    // This is required to prevent Next.js from watching files generated by App Hosting.
    serverComponentsExternalPackages: ['@whatwg-node/fetch'],
    outputFileTracingExcludes: {
      '*': [
        './.firebase/**'
      ],
    },
  },
};

module.exports = nextConfig;
